-- ============================================================================
--  电子 QSL 交换验证系统 (eQSL Exchange & Verification System)
--  MySQL 5.7+ / MariaDB 10.2+ / MySQL 8.0+
--  字符集: utf8mb4
--
--  安装:
--    mysql -u root -p -e "CREATE DATABASE qsl_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
--    mysql -u root -p qsl_db < database/schema.sql
-- ============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 1;

-- ---------------------------------------------------------------------------
-- 用户（电台台站）
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id              INT UNSIGNED NOT NULL AUTO_INCREMENT,
    callsign        VARCHAR(20)  NOT NULL COMMENT '主呼号，规范大写',
    email           VARCHAR(190) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    display_name    VARCHAR(80)  DEFAULT NULL COMMENT 'OP 姓名',
    qth             VARCHAR(120) DEFAULT NULL,
    locator         VARCHAR(12)  DEFAULT NULL COMMENT 'Maidenhead 网格',
    country         VARCHAR(80)  DEFAULT NULL,
    latitude        DECIMAL(9,5) DEFAULT NULL,
    longitude       DECIMAL(9,5) DEFAULT NULL,
    rig             VARCHAR(160) DEFAULT NULL COMMENT '设备',
    antenna         VARCHAR(160) DEFAULT NULL COMMENT '天线',
    bio             VARCHAR(600) DEFAULT NULL,
    card_image      VARCHAR(255) DEFAULT NULL COMMENT '电子卡片背景图',
    card_style      VARCHAR(20)  NOT NULL DEFAULT 'classic',
    is_admin        TINYINT(1)   NOT NULL DEFAULT 0,
    is_public       TINYINT(1)   NOT NULL DEFAULT 1 COMMENT '是否公开卡片页',
    created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_users_callsign (callsign),
    UNIQUE KEY uq_users_email    (email),
    KEY ix_users_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- 附加呼号（/P /M 便携、俱乐部台、旧呼号等），用于匹配与归户
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_callsigns (
    id        INT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id   INT UNSIGNED NOT NULL,
    callsign  VARCHAR(20)  NOT NULL,
    note      VARCHAR(120) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_alias_callsign (callsign),
    KEY ix_alias_user (user_id),
    CONSTRAINT fk_alias_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- QSO 记录
--   每条记录 = 某用户日志里的一条通联。
--   同一通联若双方都上传，会得到两条 match_key 相同的记录，交叉确认后双向 verified。
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS qsos (
    id               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id          INT UNSIGNED    NOT NULL,
    station_callsign VARCHAR(20)     NOT NULL COMMENT '本方呼号',
    call             VARCHAR(20)     NOT NULL COMMENT '对方呼号',
    qso_date         DATE            NOT NULL,
    time_on          TIME            NOT NULL COMMENT 'UTC 时:分',
    band             VARCHAR(10)     NOT NULL DEFAULT '',
    mode             VARCHAR(20)     NOT NULL DEFAULT '',
    submode          VARCHAR(20)     DEFAULT NULL,
    freq             DECIMAL(10,4)   DEFAULT NULL COMMENT 'MHz',
    rst_sent         VARCHAR(12)     NOT NULL DEFAULT '',
    rst_rcvd         VARCHAR(12)     NOT NULL DEFAULT '',
    tx_pwr           DECIMAL(6,2)    DEFAULT NULL COMMENT 'W',
    gridsquare       VARCHAR(12)     DEFAULT NULL COMMENT '对方网格',
    qth              VARCHAR(120)    DEFAULT NULL COMMENT '对方 QTH',
    name             VARCHAR(80)     DEFAULT NULL COMMENT '对方 OP',
    comment          VARCHAR(255)    DEFAULT NULL,
    match_key        CHAR(40)        NOT NULL COMMENT '归一化通联指纹 sha1',
    pair_key         CHAR(40)        NOT NULL COMMENT '呼号对指纹，用于容差候选检索',
    verify_code      CHAR(16)        NOT NULL COMMENT '公开验证码',
    verified         TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '0 待确认 1 双向已确认',
    verified_at      DATETIME        DEFAULT NULL,
    matched_qso_id   BIGINT UNSIGNED DEFAULT NULL COMMENT '对方那条记录 id',
    created_at       DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_user_match  (user_id, match_key) COMMENT '同一用户不重复记录同一通联',
    UNIQUE KEY uq_verify_code (verify_code),
    KEY ix_match_key  (match_key),
    KEY ix_pair_key   (pair_key),
    KEY ix_call       (call),
    KEY ix_user_verified (user_id, verified),
    KEY ix_user_date  (user_id, qso_date),
    CONSTRAINT fk_qso_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- 人工确认日志（容差匹配时留痕）
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS verifications (
    id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    qso_id       BIGINT UNSIGNED NOT NULL,
    peer_qso_id  BIGINT UNSIGNED NOT NULL,
    user_id      INT UNSIGNED    NOT NULL COMMENT '发起确认的人',
    method       ENUM('auto','manual') NOT NULL DEFAULT 'auto',
    created_at   DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY ix_ver_qso (qso_id),
    KEY ix_ver_peer (peer_qso_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- DXCC 前缀表（精简常用实体，可自行扩充）
-- 匹配规则：按 prefix 长度降序，取呼号的最长前缀命中
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dxcc (
    id        INT UNSIGNED NOT NULL AUTO_INCREMENT,
    prefix    VARCHAR(12)  NOT NULL,
    entity    VARCHAR(80)  NOT NULL,
    continent VARCHAR(2)   NOT NULL DEFAULT '',
    cq_zone   TINYINT UNSIGNED DEFAULT NULL,
    itu_zone  TINYINT UNSIGNED DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_dxcc_prefix (prefix)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO dxcc (prefix, entity, continent, cq_zone, itu_zone) VALUES
('1A',  'Sovereign Military Order of Malta', 'EU', 15, 28),
('3B6', 'Agalega & St Brandon', 'AF', 39, 53),
('3B8', 'Mauritius', 'AF', 39, 53),
('3B9', 'Rodrigues Island', 'AF', 39, 53),
('3D2', 'Fiji', 'OC', 32, 56),
('3DA', 'Eswatini', 'AF', 38, 57),
('3V',  'Tunisia', 'AF', 33, 37),
('3W',  'Vietnam', 'AS', 26, 49),
('3X',  'Guinea', 'AF', 35, 46),
('3Y',  'Bouvet Island', 'AF', 38, 68),
('4J',  'Azerbaijan', 'AS', 21, 29),
('4K',  'Azerbaijan', 'AS', 21, 29),
('4L',  'Georgia', 'AS', 21, 29),
('4S',  'Sri Lanka', 'AS', 22, 41),
('4U1U','United Nations HQ', 'NA', 5, 8),
('4X',  'Israel', 'AS', 20, 39),
('4Z',  'Israel', 'AS', 20, 39),
('5A',  'Libya', 'AF', 34, 38),
('5B',  'Cyprus', 'EU', 20, 39),
('5H',  'Tanzania', 'AF', 37, 53),
('5N',  'Nigeria', 'AF', 35, 46),
('5R',  'Madagascar', 'AF', 39, 53),
('5T',  'Mauritania', 'AF', 35, 46),
('5U',  'Niger', 'AF', 35, 46),
('5V',  'Togo', 'AF', 35, 46),
('5W',  'Samoa', 'OC', 32, 62),
('5X',  'Uganda', 'AF', 37, 52),
('5Z',  'Kenya', 'AF', 37, 53),
('6W',  'Senegal', 'AF', 35, 46),
('6Y',  'Jamaica', 'NA', 8, 11),
('7P',  'Lesotho', 'AF', 38, 57),
('7Q',  'Malawi', 'AF', 37, 53),
('7X',  'Algeria', 'AF', 33, 37),
('8P',  'Barbados', 'NA', 8, 11),
('8Q',  'Maldives', 'AS', 22, 41),
('8R',  'Guyana', 'SA', 9, 12),
('9A',  'Croatia', 'EU', 15, 28),
('9G',  'Ghana', 'AF', 35, 46),
('9H',  'Malta', 'EU', 15, 28),
('9J',  'Zambia', 'AF', 36, 53),
('9K',  'Kuwait', 'AS', 21, 39),
('9L',  'Sierra Leone', 'AF', 35, 46),
('9M',  'West Malaysia', 'AS', 28, 54),
('9N',  'Nepal', 'AS', 22, 42),
('9Q',  'DR Congo', 'AF', 36, 52),
('9U',  'Burundi', 'AF', 36, 52),
('9V',  'Singapore', 'AS', 28, 54),
('9X',  'Rwanda', 'AF', 36, 52),
('9Y',  'Trinidad & Tobago', 'NA', 8, 11),
('A2',  'Botswana', 'AF', 38, 57),
('A3',  'Tonga', 'OC', 32, 62),
('A4',  'Oman', 'AS', 21, 39),
('A5',  'Bhutan', 'AS', 22, 41),
('A6',  'United Arab Emirates', 'AS', 21, 39),
('A7',  'Qatar', 'AS', 21, 39),
('A9',  'Bahrain', 'AS', 21, 39),
('AP',  'Pakistan', 'AS', 21, 41),
('BV',  'Taiwan, China', 'AS', 24, 44),
('BY',  'China', 'AS', 24, 44),
('C2',  'Nauru', 'OC', 31, 65),
('C3',  'Andorra', 'EU', 14, 27),
('C5',  'Gambia', 'AF', 35, 46),
('C6',  'Bahamas', 'NA', 8, 11),
('C9',  'Mozambique', 'AF', 37, 53),
('CA',  'Chile', 'SA', 12, 14),
('CE',  'Chile', 'SA', 12, 14),
('CM',  'Cuba', 'NA', 8, 11),
('CN',  'Morocco', 'AF', 33, 37),
('CO',  'Cuba', 'NA', 8, 11),
('CP',  'Bolivia', 'SA', 10, 12),
('CT',  'Portugal', 'EU', 14, 37),
('CT3', 'Madeira Islands', 'AF', 33, 36),
('CU',  'Azores', 'EU', 14, 36),
('CX',  'Uruguay', 'SA', 13, 14),
('D2',  'Angola', 'AF', 36, 52),
('D4',  'Cape Verde', 'AF', 35, 46),
('D6',  'Comoros', 'AF', 39, 53),
('DL',  'Germany', 'EU', 14, 28),
('DU',  'Philippines', 'OC', 27, 50),
('E3',  'Eritrea', 'AF', 37, 47),
('E4',  'Palestine', 'AS', 20, 39),
('E5',  'South Cook Islands', 'OC', 32, 63),
('E7',  'Bosnia-Herzegovina', 'EU', 15, 28),
('EA',  'Spain', 'EU', 14, 37),
('EA6', 'Balearic Islands', 'EU', 14, 37),
('EA8', 'Canary Islands', 'AF', 33, 36),
('EA9', 'Ceuta & Melilla', 'AF', 33, 37),
('EI',  'Ireland', 'EU', 14, 27),
('EK',  'Armenia', 'AS', 21, 29),
('EL',  'Liberia', 'AF', 35, 46),
('EP',  'Iran', 'AS', 21, 40),
('ER',  'Moldova', 'EU', 16, 29),
('ES',  'Estonia', 'EU', 15, 29),
('ET',  'Ethiopia', 'AF', 37, 47),
('EU',  'Belarus', 'EU', 16, 29),
('EX',  'Kyrgyzstan', 'AS', 17, 30),
('EY',  'Tajikistan', 'AS', 17, 30),
('EZ',  'Turkmenistan', 'AS', 17, 30),
('F',   'France', 'EU', 14, 27),
('FG',  'Guadeloupe', 'NA', 8, 11),
('FH',  'Mayotte', 'AF', 39, 53),
('FJ',  'St Barthelemy', 'NA', 8, 11),
('FK',  'New Caledonia', 'OC', 32, 56),
('FM',  'Martinique', 'NA', 8, 11),
('FO',  'French Polynesia', 'OC', 32, 63),
('FP',  'St Pierre & Miquelon', 'NA', 5, 8),
('FR',  'Reunion Island', 'AF', 39, 53),
('FT',  'French Antarctic', 'AN', 39, 68),
('FW',  'Wallis & Futuna', 'OC', 32, 62),
('FY',  'French Guiana', 'SA', 9, 12),
('G',   'England', 'EU', 14, 27),
('GD',  'Isle of Man', 'EU', 14, 27),
('GI',  'Northern Ireland', 'EU', 14, 27),
('GJ',  'Jersey', 'EU', 14, 27),
('GM',  'Scotland', 'EU', 14, 27),
('GU',  'Guernsey', 'EU', 14, 27),
('GW',  'Wales', 'EU', 14, 27),
('H4',  'Solomon Islands', 'OC', 28, 51),
('HA',  'Hungary', 'EU', 15, 28),
('HB',  'Switzerland', 'EU', 14, 28),
('HB0', 'Liechtenstein', 'EU', 14, 28),
('HC',  'Ecuador', 'SA', 10, 12),
('HC8', 'Galapagos Islands', 'SA', 10, 12),
('HH',  'Haiti', 'NA', 8, 11),
('HI',  'Dominican Republic', 'NA', 8, 11),
('HK',  'Colombia', 'SA', 9, 12),
('HK0', 'San Andres & Providencia', 'NA', 7, 11),
('HL',  'South Korea', 'AS', 25, 44),
('HP',  'Panama', 'NA', 7, 11),
('HR',  'Honduras', 'NA', 7, 11),
('HS',  'Thailand', 'AS', 26, 49),
('HV',  'Vatican City', 'EU', 15, 28),
('HZ',  'Saudi Arabia', 'AS', 21, 39),
('I',   'Italy', 'EU', 15, 28),
('IS',  'Sardinia', 'EU', 15, 28),
('J2',  'Djibouti', 'AF', 37, 48),
('J3',  'Grenada', 'NA', 8, 11),
('J5',  'Guinea-Bissau', 'AF', 35, 46),
('J6',  'St Lucia', 'NA', 8, 11),
('J7',  'Dominica', 'NA', 8, 11),
('J8',  'St Vincent', 'NA', 8, 11),
('JA',  'Japan', 'AS', 25, 45),
('JD1', 'Minami Torishima', 'OC', 27, 43),
('JT',  'Mongolia', 'AS', 23, 32),
('JW',  'Svalbard', 'EU', 40, 18),
('JX',  'Jan Mayen', 'EU', 40, 18),
('K',   'United States', 'NA', 5, 8),
('KH0', 'Mariana Islands', 'OC', 27, 64),
('KH1', 'Baker & Howland Islands', 'OC', 31, 61),
('KH2', 'Guam', 'OC', 27, 64),
('KH3', 'Johnston Island', 'OC', 31, 61),
('KH4', 'Midway Island', 'OC', 31, 61),
('KH5', 'Palmyra & Jarvis Islands', 'OC', 31, 61),
('KH6', 'Hawaii', 'OC', 31, 61),
('KH7', 'Kure Island', 'OC', 31, 61),
('KH8', 'American Samoa', 'OC', 32, 62),
('KH9', 'Wake Island', 'OC', 31, 64),
('KL',  'Alaska', 'NA', 1, 3),
('KP1', 'Navassa Island', 'NA', 8, 11),
('KP2', 'US Virgin Islands', 'NA', 8, 11),
('KP4', 'Puerto Rico', 'NA', 8, 11),
('LA',  'Norway', 'EU', 14, 18),
('LU',  'Argentina', 'SA', 13, 14),
('LX',  'Luxembourg', 'EU', 14, 27),
('LY',  'Lithuania', 'EU', 15, 29),
('LZ',  'Bulgaria', 'EU', 20, 28),
('OA',  'Peru', 'SA', 10, 12),
('OD',  'Lebanon', 'AS', 20, 39),
('OE',  'Austria', 'EU', 15, 28),
('OH',  'Finland', 'EU', 15, 18),
('OH0', 'Aland Islands', 'EU', 15, 18),
('OK',  'Czech Republic', 'EU', 15, 28),
('OM',  'Slovak Republic', 'EU', 15, 28),
('ON',  'Belgium', 'EU', 14, 27),
('OX',  'Greenland', 'NA', 40, 5),
('OY',  'Faroe Islands', 'EU', 14, 18),
('OZ',  'Denmark', 'EU', 14, 18),
('P2',  'Papua New Guinea', 'OC', 28, 51),
('P4',  'Aruba', 'SA', 9, 11),
('P5',  'North Korea', 'AS', 25, 44),
('PA',  'Netherlands', 'EU', 14, 27),
('PJ2', 'Curacao', 'SA', 9, 11),
('PJ4', 'Bonaire', 'SA', 9, 11),
('PJ5', 'Saba & St Eustatius', 'NA', 8, 11),
('PJ7', 'Sint Maarten', 'NA', 8, 11),
('PY',  'Brazil', 'SA', 11, 13),
('PY0', 'Fernando de Noronha', 'SA', 11, 13),
('PZ',  'Suriname', 'SA', 9, 12),
('R',   'Asiatic Russia', 'AS', 17, 30),
('S0',  'Western Sahara', 'AF', 35, 46),
('S2',  'Bangladesh', 'AS', 22, 41),
('S5',  'Slovenia', 'EU', 15, 28),
('S7',  'Seychelles', 'AF', 39, 53),
('S9',  'Sao Tome & Principe', 'AF', 36, 47),
('SA',  'Sweden', 'EU', 14, 18),
('SM',  'Sweden', 'EU', 14, 18),
('SP',  'Poland', 'EU', 15, 28),
('ST',  'Sudan', 'AF', 34, 47),
('SU',  'Egypt', 'AF', 34, 38),
('SV',  'Greece', 'EU', 20, 28),
('SV9', 'Crete', 'EU', 20, 28),
('T2',  'Tuvalu', 'OC', 31, 65),
('T30', 'Central Kiribati', 'OC', 31, 65),
('T32', 'Eastern Kiribati', 'OC', 31, 61),
('T33', 'Banaba Island', 'OC', 31, 65),
('T5',  'Somalia', 'AF', 37, 48),
('T7',  'San Marino', 'EU', 15, 28),
('T8',  'Palau', 'OC', 27, 64),
('TA',  'Turkey', 'AS', 20, 39),
('TF',  'Iceland', 'EU', 40, 17),
('TG',  'Guatemala', 'NA', 7, 11),
('TI',  'Costa Rica', 'NA', 7, 11),
('TI9', 'Cocos Island', 'NA', 7, 11),
('TJ',  'Cameroon', 'AF', 36, 47),
('TK',  'Corsica', 'EU', 15, 28),
('TL',  'Central African Republic', 'AF', 36, 47),
('TN',  'Congo Republic', 'AF', 36, 52),
('TR',  'Gabon', 'AF', 36, 47),
('TT',  'Chad', 'AF', 36, 47),
('TU',  'Ivory Coast', 'AF', 35, 46),
('TY',  'Benin', 'AF', 35, 46),
('TZ',  'Mali', 'AF', 35, 46),
('UA',  'European Russia', 'EU', 16, 29),
('UA0', 'Asiatic Russia', 'AS', 23, 33),
('UK',  'Uzbekistan', 'AS', 17, 30),
('UN',  'Kazakhstan', 'AS', 17, 29),
('UR',  'Ukraine', 'EU', 16, 29),
('V2',  'Antigua & Barbuda', 'NA', 8, 11),
('V3',  'Belize', 'NA', 7, 11),
('V4',  'St Kitts & Nevis', 'NA', 8, 11),
('V5',  'Namibia', 'AF', 38, 57),
('V6',  'Micronesia', 'OC', 27, 65),
('V7',  'Marshall Islands', 'OC', 31, 65),
('V8',  'Brunei', 'OC', 28, 54),
('VE',  'Canada', 'NA', 5, 4),
('VK',  'Australia', 'OC', 29, 55),
('VK0', 'Antarctica', 'AN', 30, 69),
('VK9', 'Cocos-Keeling / Christmas Island', 'OC', 29, 54),
('VP2E','Anguilla', 'NA', 8, 11),
('VP2M','Montserrat', 'NA', 8, 11),
('VP2V','British Virgin Islands', 'NA', 8, 11),
('VP5', 'Turks & Caicos Islands', 'NA', 8, 11),
('VP6', 'Pitcairn Island', 'OC', 32, 63),
('VP8', 'Falkland Islands', 'SA', 13, 16),
('VP9', 'Bermuda', 'NA', 5, 9),
('VQ9', 'Chagos Islands', 'AF', 39, 41),
('VR',  'Hong Kong, China', 'AS', 24, 44),
('VU',  'India', 'AS', 22, 41),
('VU7', 'Lakshadweep Islands', 'AS', 22, 41),
('W',   'United States', 'NA', 5, 8),
('XE',  'Mexico', 'NA', 6, 10),
('XF4', 'Revilla Gigedo Islands', 'NA', 6, 10),
('XT',  'Burkina Faso', 'AF', 35, 46),
('XU',  'Cambodia', 'AS', 26, 49),
('XV',  'Vietnam', 'AS', 26, 49),
('XW',  'Laos', 'AS', 26, 49),
('XX',  'Macao, China', 'AS', 24, 44),
('YA',  'Afghanistan', 'AS', 21, 40),
('YB',  'Indonesia', 'OC', 28, 54),
('YI',  'Iraq', 'AS', 21, 39),
('YJ',  'Vanuatu', 'OC', 32, 56),
('YK',  'Syria', 'AS', 20, 39),
('YL',  'Latvia', 'EU', 15, 29),
('YN',  'Nicaragua', 'NA', 7, 11),
('YO',  'Romania', 'EU', 20, 28),
('YS',  'El Salvador', 'NA', 7, 11),
('YU',  'Serbia', 'EU', 15, 28),
('YV',  'Venezuela', 'SA', 9, 12),
('YV0', 'Aves Island', 'SA', 8, 11),
('Z2',  'Zimbabwe', 'AF', 38, 53),
('Z3',  'North Macedonia', 'EU', 15, 28),
('Z6',  'Kosovo', 'EU', 15, 28),
('Z8',  'South Sudan', 'AF', 34, 47),
('ZA',  'Albania', 'EU', 15, 28),
('ZB',  'Gibraltar', 'EU', 14, 37),
('ZC4', 'UK Sovereign Base Area Cyprus', 'AS', 20, 39),
('ZD7', 'St Helena', 'AF', 36, 66),
('ZD8', 'Ascension Island', 'AF', 36, 66),
('ZD9', 'Tristan da Cunha', 'AF', 38, 66),
('ZF',  'Cayman Islands', 'NA', 8, 11),
('ZK3', 'Tokelau Islands', 'OC', 31, 62),
('ZL',  'New Zealand', 'OC', 32, 60),
('ZL7', 'Chatham Islands', 'OC', 32, 60),
('ZL8', 'Kermadec Islands', 'OC', 32, 60),
('ZL9', 'Auckland & Campbell Islands', 'OC', 32, 60),
('ZP',  'Paraguay', 'SA', 11, 14),
('ZR',  'South Africa', 'AF', 38, 57),
('ZS',  'South Africa', 'AF', 38, 57),
('ZS8', 'Prince Edward & Marion Islands', 'AF', 38, 57);

-- 常见美国/加拿大/中国细分呼号前缀（辅助匹配）
INSERT INTO dxcc (prefix, entity, continent, cq_zone, itu_zone) VALUES
('AA','United States','NA',5,8),('AB','United States','NA',5,8),
('AC','United States','NA',5,8),('AD','United States','NA',5,8),
('AE','United States','NA',5,8),('AF','United States','NA',5,8),
('AG','United States','NA',5,8),('AI','United States','NA',5,8),
('AJ','United States','NA',5,8),('AK','United States','NA',5,8),
('AL','United States','NA',5,8),('AM','United States','NA',5,8),
('AN','United States','NA',5,8),('AO','United States','NA',5,8),
('N','United States','NA',5,8),
('BA','China','AS',24,44),('BD','China','AS',24,44),
('BG','China','AS',24,44),('BH','China','AS',24,44),
('BI','China','AS',24,44),('BJ','China','AS',24,44),
('BL','China','AS',24,44),('BM','China','AS',24,44),
('BN','China','AS',24,44),('BO','China','AS',24,44),
('BP','China','AS',24,44),('BQ','China','AS',24,44),
('BR','China','AS',24,44),('BT','China','AS',24,44);

-- ---------------------------------------------------------------------------
-- 系统设置（可选扩展）
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS settings (
    k VARCHAR(64) NOT NULL,
    v VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (k)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO settings (k, v) VALUES
('site_name',      'eQSL 交换验证系统'),
('site_slogan',    'QSL 交换 · 双向验证 · DXCC 统计'),
('allow_register', '1'),
('installed_at',   NOW())
ON DUPLICATE KEY UPDATE v = VALUES(v);
